{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6002fdb3-eb33-4ace-92cc-bdfb4b757343",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q1. What is an Exception in python? Write the difference between Exceptions\n",
    "and Syntax errors ?\n",
    "\n",
    "An exception in Python is an incident that happens while executing a \n",
    "program that causes the regular courses of the  programs commands to be \n",
    "disrupted. When a Python code comes across a condition it cant handle, \n",
    "it raises an exception. An object in Python that describes an error is called \n",
    "an exception.\n",
    "\n",
    "Synatx Error: Errors which are caused due to syntactical error ,or to be\n",
    "more specific grammatical error.\n",
    "For E.g:\n",
    "print('Hi ...My name is ..\")\n",
    "      \n",
    "Exceptions :Exceptions are those when the Python code is syntatctically \n",
    "correct but during runtime, the compiler faces some error,\n",
    "so it is not able to execute the program.\n",
    "      \n",
    "For Example:\n",
    "prit('Hello..My Name is..')\n",
    "      "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ed5efdbe-3877-4915-96c9-e89ffdfaf7b2",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q2. What happens when an exception is not handled? Explain with\n",
    "an example.\n",
    "\n",
    "When an exception is not handled then the program will close\n",
    "abrubtly and the lines after the exception will not be excuted\n",
    "and the compiler will throw an exception.\n",
    "\n",
    "Correct Program:\n",
    "print('Hello There ')\n",
    "for _ in range(1,5):\n",
    "    print('--*--*',end='')\n",
    "    \n",
    "Note: In the correct program , since there are no errors, the whole program will \n",
    "excute.\n",
    "\n",
    "Program with Exception:\n",
    "\n",
    "prit('Hello There ')\n",
    "for _ in range(1,5):\n",
    "    print('--*--*',end='')  \n",
    "    \n",
    "Note: In the program with exception, since the spelling of print is wrong , it would \n",
    "throw a 'NameError' and the program after that will not be executed.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d919d2e0-24eb-4c62-ab14-bbb4e5c2ebec",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q3. Which Python statements are used to catch and handle exceptions?\n",
    "Explain with an example.\n",
    "\n",
    "The try and except block in Python is used to catch and handle exceptions.\n",
    "For Example:\n",
    "try:\n",
    "    prit('Hello my name is ..')\n",
    "except NameError as e:\n",
    "    print(e)\n",
    "except Exception as ex:\n",
    "    print(ex)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c0200785-529e-462c-886e-ab3f4be18ba1",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q4. Explain with an example:\n",
    "a.try and else\n",
    "\n",
    "try:\n",
    "    print('Hello this is ..')\n",
    "except Exception as e:\n",
    "    print(e)\n",
    "else:\n",
    "    print('This will  execute when no exception is found')\n",
    "\n",
    "Note:If the try block contains no exception than the try block\n",
    "will run without any problem ,it will skip the except block as there \n",
    "is no exception.and the control will go to the else block and execte the else block.\n",
    "\n",
    "\n",
    "b.finally\n",
    "\n",
    "try:\n",
    "    print('Hello this is ..')\n",
    "except Exception as e:\n",
    "    print(e)\n",
    "else:\n",
    "    print('This will  execute when no exception is found')\n",
    "finally:\n",
    "    print('THis will execute no matter what the exception is there or not')\n",
    "\n",
    "Note:\n",
    "Same as above, but irrespective of the error is present or not,the \n",
    "finally block will always excute.\n",
    "\n",
    "\n",
    "c.raise\n",
    "\n",
    "s=input('Enter the name :')\n",
    "if len(s)==0 or s.isdigit() or s==' ' or s.isalnum()==False:\n",
    "    raise Exception(f'The Name given is not valid ..Please enter a Valid name')\n",
    "else:\n",
    "    print('Thank you ..{} for confirming'.format(s))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1adce9d7-26d2-4f0f-83c4-aee93eed24be",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q5. What are Custom Exceptions in python? Why\n",
    "do we need Custom Exceptions? Explain with\n",
    "an example ?\n",
    "\n",
    "Custom Exception are exception created by the user as per his/her's\n",
    "need to tacle a specic type of error.\n",
    "We use Custom Exception because it enhances the ease in \n",
    "debugging and we get customized error messages so that \n",
    "the debgging becomes easily traceble.\n",
    "\n",
    "class InvalidAgeException(Exception):\n",
    "    def __init__(self):\n",
    "        print('Hi..I am from InvalidAgeException')\n",
    "\n",
    "# you need to guess this number\n",
    "number = 18\n",
    "\n",
    "try:\n",
    "    input_num = int(input(\"Enter a number: \"))\n",
    "    if input_num < number:\n",
    "        raise InvalidAgeException\n",
    "    else:\n",
    "        print(\"Eligible to Vote\")\n",
    "        \n",
    "except InvalidAgeException :\n",
    "    print(\"Exception occurred: Invalid Age\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2da0eee4-efb0-40be-9961-1f9b72eba1b4",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q6. Create custom exception class. Use this class to handle\n",
    "an exception.\n",
    "\n",
    "class InvalidAgeException(Exception):\n",
    "    def __init__(self):\n",
    "        print('Hi..I am from InvalidAgeException')\n",
    "\n",
    "# you need to guess this number\n",
    "number = 18\n",
    "\n",
    "try:\n",
    "    input_num = int(input(\"Enter a number: \"))\n",
    "    if input_num < number:\n",
    "        raise InvalidAgeException\n",
    "    else:\n",
    "        print(\"Eligible to Vote\")\n",
    "        \n",
    "except InvalidAgeException :\n",
    "    print(\"Exception occurred: Invalid Age\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1c0fc4f6-546c-46e0-9cf4-77e173e70472",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
